### PR TITLE
Remove *10 from delay and set default speed to 50.

### PR DESCRIPTION
**Pull request by ghost**
With this change the default speed is higher and looks a lot smoother, and you get much more control of the speed at high -s numbers.
You can still set the same speeds with negative numbers so i don't think there are any issues with this change.

### CODE REVIEW

**Comment by will8211** [comment]
Hmm, I agree that fine grained control would be good at higher speeds, but now we have to go quite far below 0 to get a slow speed. Also, I sort of like to have all the speeds that someone might want to use in the range of 0 to 100. What if we keep my numbering system, but allow floating point speeds so people can go up or down by 0.1 using ,/.

**Comment by ghost** [comment]
That should work as well, my only issues with the speed system is the default speed and lack of fine control at high speeds. Though if you're gonna keep negative speed values i don't see the point in keeping values between 0-100.
(nice work btw, i hope i don't come off as nitpicky..)

**Comment by ghost** [comment]
God sorry for the commit mess, i'm still not used to github..

**Comment by will8211** [comment]
Will rework the speed controls in v2.

**Comment by will8211** [comment]
Will be fixed in [MTRX-4](https://trello.com/c/3q7YDLts/3-mtrx-4-use-logarithmic-scale-for-speed-control-and-set-faster-default)

[MTRX-4]: https://astrocharts.atlassian.net/browse/MTRX-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Pull request closed without merging**
