### PR TITLE
Add new features of randomly change char sets during running

### PR DESCRIPTION
**Pull request by CesareMJLi**
Hi :)

I quite like this project and I made some own modifications on unimatrix.py

In the class of **KeyHandler** from **line 529 to line 541**

. I set a new function, you could press '`' (the key on the left of number 1) to randomly change the original char set.

I test it on my mac. There's some difference on the terminal that the emoji does not shows well here. But as for the rest I think it's ok.

Merge it if you like this modification.

(It's my first time to pull a request. If there's anything not clear please let me know)

Anyway, this project is a great work. Good job and thank you for your sharing ;)

### CODE REVIEW

**Comment by will8211** [comment]
Hi! Sorry it's taken me a while to check your commit. 
Could you please resubmit it? Your current request is to 

> merge into `revert-14-patch-2` from `master`

It should be something like

> merge into `will8211:master` from `CesareMJLi:[branch_name]`

Thanks!

**Comment by CesareMJLi** [comment]
Hi. I replied this request, and I hope this time I do it rightly.

Best
Yours Faithfully

**Comment by petaflot** [comment]
my suggestion is that should be done so:

since the charsets is a list that can contain more occurrences of the same set (to increase frquency) there should be a way to add/delete items from that list, ie `-` followed by a letter to remove and `+` followed by a letter to add.

having a command-line argument to automatically change sets would be cool too

being able to SIG-something from another process to change that (and color!) would really be cool (and actually useful)

**Comment by will8211** [comment]
Hi! Thanks for your interest in the project. After having been inactive for some time, I'm taking up the project again. I'll have a look at this PR soon.

**Pull request closed without merging**
